/*  =========================================================================
    zlogger - ZLOGGER wrapper

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of zproject-zproto:                              
    http://github.com/danriegsecker/zproject-zproto.                   
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef __zlogger_library_H_INCLUDED__
#define __zlogger_library_H_INCLUDED__

//  External dependencies
#include <czmq.h>

//  ZLOGGER version macros for compile-time API detection

#define ZLOGGER_VERSION_MAJOR 1
#define ZLOGGER_VERSION_MINOR 0
#define ZLOGGER_VERSION_PATCH 0

#define ZLOGGER_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZLOGGER_VERSION \
    ZLOGGER_MAKE_VERSION(ZLOGGER_VERSION_MAJOR, ZLOGGER_VERSION_MINOR, ZLOGGER_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBZLOGGER_STATIC
#       define ZLOGGER_EXPORT
#   elif defined LIBZLOGGER_EXPORTS
#       define ZLOGGER_EXPORT __declspec(dllexport)
#   else
#       define ZLOGGER_EXPORT __declspec(dllimport)
#   endif
#else
#   define ZLOGGER_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _zlog_msg_t zlog_msg_t;
#define ZLOG_MSG_T_DEFINED
typedef struct _zlog_server_t zlog_server_t;
#define ZLOG_SERVER_T_DEFINED
typedef struct _zlog_client_t zlog_client_t;
#define ZLOG_CLIENT_T_DEFINED


//  Public API classes
#include "zlog_msg.h"
#include "zlog_server.h"
#include "zlog_client.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
